development:
  adapter: postgresql
  encoding: unicode
  reconnect: true
  database: himholod
  pool: 5
  username: himholod
  password: dSL8GtsrSJr
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  reconnect: true
  database: himholod_test
  pool: 5
  username: himholod
  password: dSL8GtsrSJr
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  reconnect: true
  database: himholod
  pool: 5
  username: himholod
  password: dSL8GtsrSJr
  host: 127.0.0.1
